location_types:
  # Define the main types of locations relevant to your domain
  
  primary_location:
    description: "Main locations central to football"
    examples: ["Key Location 1", "Important Place"]
    
  country:
    description: "Nations and countries"
    examples: ["United States", "United Kingdom"]
    
  city:
    description: "Cities and towns"
    examples: ["New York", "London"]
    
  region:
    description: "Geographic regions, states, provinces"
    examples: ["California", "European Union"]
    
  facility:
    description: "Specific buildings, installations, or facilities"
    examples: ["Building Name", "Facility"]
    
  venue:
    description: "Event venues, meeting places, or gathering locations"
    examples: ["Conference Center", "Stadium"]
    
  other:
    description: "Any other location type not covered above"
    examples: []

# Instructions for customization:
# 1. Replace football with your domain
# 2. Update location_types to match your domain's key locations
# 3. Provide clear descriptions and real examples
# 4. Remove any types that don't apply to your domain
# 5. Add new types as needed