organization_types:
  # Define the main types of organizations relevant to your domain
  
  primary_organization:
    description: "Main organizations central to football"
    examples: ["Primary Org 1", "Primary Org 2"]
    
  government:
    description: "Government entities and departments"
    examples: ["Government Agency", "Department Name"]
    
  private_sector:
    description: "Private companies and businesses"
    examples: ["Company Name", "Corporation"]
    
  non_profit:
    description: "Non-profit organizations and NGOs"
    examples: ["NGO Name", "Foundation"]
    
  media:
    description: "Media organizations and news outlets"
    examples: ["News Organization", "Media Company"]
    
  academic:
    description: "Academic institutions and research organizations"
    examples: ["University", "Research Institute"]
    
  other:
    description: "Any other organization type not covered above"
    examples: []

# Instructions for customization:
# 1. Replace football with your domain
# 2. Update organization_types to match your domain's key organizations
# 3. Provide clear descriptions and real examples
# 4. Remove any types that don't apply to your domain
# 5. Add new types as needed