person_types:
  # Define the main types of people relevant to your research domain
  # Each type should have a clear description and examples
  # Consider the historical context and time period of your research
  
  primary_actor:
    description: "Main historical figures or participants in football"
    examples: ["Historical Figure 1", "Key Participant 2"]
    
  official:
    description: "Government officials, authorities, or decision-makers"
    examples: ["Political Leader", "Administrator"]
    
  scholar:
    description: "Academics, researchers, or intellectuals studying/documenting the topic"
    examples: ["Historian Name", "Research Scholar"]
    
  witness:
    description: "Eyewitnesses, contemporaries, or people who experienced events firsthand"
    examples: ["Contemporary Observer", "Participant"]
    
  chronicler:
    description: "Writers, journalists, or documentarians recording events"
    examples: ["Chronicle Writer", "Contemporary Journalist"]
    
  other:
    description: "Any other type of person not covered above"
    examples: []

person_tags:
  # Define tags for additional categorization beyond person types
  # Tags provide more granular classification and can be combined
  # Multiple tags can be assigned to a single person
  
  role_tag1:
    description: "Tag for people in a specific role or function"
    examples: ["Role example 1", "Role example 2"]
    
  context_tag1:
    description: "Tag for people in a specific context or situation"
    examples: ["Context example 1", "Context example 2"]
    
  affiliation_tag1:
    description: "Tag for people with specific organizational affiliations"
    examples: ["Organization member", "Institution affiliate"]
    
  other:
    description: "Any other tag not covered by the above categories"
    examples: []

# Instructions for customization:
# 1. Replace football with your research domain
# 2. Update person_types to match your historical period's key roles
# 3. Update person_tags to provide additional categorization
# 4. Provide clear descriptions and real historical examples
# 5. Consider the social/political context of your time period
# 6. Remove any types/tags that don't apply to your research area
# 7. Add new types/tags specific to your historical context