domain: "football"
description: "Articles and analysis related to football"

# Data source configuration
data_sources:
  default_path: "data/football/raw_sources/football_articles.parquet"

# Output configuration  
output:
  directory: "data/football/entities"

# Similarity threshold for entity deduplication (0.0-1.0)
similarity_threshold: 0.75

# Processing configuration
processing:
  # Enable relevance checking before extraction
  relevance_check: true
  
  # Batch size for processing articles
  batch_size: 5