"""Initial migration

Revision ID: 72d2b0000b8a
Revises:
Create Date: 2025-02-19 09:06:14.697125

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "72d2b0000b8a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
