person_types:
  detainee:
    description: "A person who is or was detained at Guantánamo Bay or another detention facility"
    examples: ["Mohamedou Ould Slahi", "David Hicks", "Khalid Sheikh Mohammed"]
    
  military:
    description: "Military personnel including soldiers, officers, and other armed forces members"
    examples: ["General Geoffrey Miller", "Admiral Harry Harris", "Colonel Morris Davis"]
    
  government:
    description: "Government officials, politicians, and civil servants"
    examples: ["Donald Rumsfeld", "Barack Obama", "Eric Holder"]
    
  lawyer:
    description: "Attorneys, legal representatives, and other legal professionals"
    examples: ["Clive Stafford Smith", "Gitanjali Gutierrez", "David Remes"]
    
  journalist:
    description: "Reporters, writers, and other media professionals"
    examples: ["Carol Rosenberg", "Andy Worthington", "Jason Leopold"]
    
  other:
    description: "Any other type of person not covered by the above categories"
    examples: []

person_tags:
  civil_rights:
    description: "People involved in civil rights advocacy or organizations"
    examples: ["ACLU lawyers", "Human rights activists"]
    
  immigration:
    description: "People involved in immigration law or policy"
    examples: ["Immigration lawyers", "ICE officials"]
    
  defense:
    description: "People involved in defense or military defense roles"
    examples: ["Defense attorneys", "Military defense counsel"]
    
  prosecution:
    description: "People involved in prosecution or legal enforcement"
    examples: ["Prosecutors", "FBI agents"]
    
  policy:
    description: "People involved in policy making or administration"
    examples: ["Cabinet members", "Policy advisors"]
    
  medical:
    description: "Medical professionals and healthcare workers"
    examples: ["Doctors", "Psychiatrists", "Medical staff"]
    
  intelligence:
    description: "Intelligence agency personnel and analysts"
    examples: ["CIA agents", "Intelligence analysts"]
    
  academic:
    description: "Academics, researchers, and scholars"
    examples: ["University professors", "Research fellows"]
    
  religious:
    description: "Religious figures and chaplains"
    examples: ["Military chaplains", "Religious leaders"]
    
  family:
    description: "Family members of detainees or other key figures"
    examples: ["Detainee family members", "Victims' families"]
    
  activist:
    description: "Activists and advocacy group members"
    examples: ["Protesters", "Campaign organizers"]
    
  other:
    description: "Any other tag not covered by the above categories"
    examples: []