name: Claude Auto Review with Tracking
on:
  issue_comment:
    types: [created]

jobs:
  review:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@claude stefan-review') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          track_progress: true # ✨ Enables tracking comments
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.issue.number }}

            COMMENT AUTHOR: ${{ github.event.comment.user.login }}
            COMMENT ID: ${{ github.event.comment.id }}
            COMMENT BODY:
            ---
            ${{ github.event.comment.body }}
            ---

            Please review this pull request using the stefan-reviewer subagent.

            Provide detailed feedback using inline comments for specific issues.
            When posting inline comments, use the tool "create_inline_comment" with parameters:
            - path, body, line, startLine, side, commit_id
            Anchor comments to the PR head commit and use side="RIGHT".

          claude_args: |
            --mcp-config '{
              "mcpServers": {
                "github_comment": {
                  "command": "bun",
                  "args": ["run", "/home/runner/work/_actions/anthropics/claude-code-action/v1/src/mcp/github-comment-server.ts"],
                  "env": {
                    "GITHUB_TOKEN": "${{ github.token }}",
                    "REPO_OWNER": "${{ github.repository_owner }}",
                    "REPO_NAME": "${{ github.event.repository.name }}",
                    "CLAUDE_COMMENT_ID": "${{ steps.prepare.outputs.comment_id }}",
                    "GITHUB_EVENT_NAME": "${{ github.event_name }}",
                    "GITHUB_API_URL": "https://api.github.com"
                  }
                },
                "github_ci": {
                  "command": "bun",
                  "args": ["run", "/home/runner/work/_actions/anthropics/claude-code-action/v1/src/mcp/github-actions-server.ts"],
                  "env": {
                    "GITHUB_TOKEN": "${{ github.token }}",
                    "REPO_OWNER": "${{ github.repository_owner }}",
                    "REPO_NAME": "${{ github.event.repository.name }}",
                    "PR_NUMBER": "${{ github.event.issue.number }}",
                    "RUNNER_TEMP": "${{ runner.temp }}"
                  }
                },
                "github_inline_comment": {
                  "command": "bun",
                  "args": ["run", "/home/runner/work/_actions/anthropics/claude-code-action/v1/src/mcp/github-inline-comment-server.ts"],
                  "env": {
                    "GITHUB_TOKEN": "${{ github.token }}",
                    "REPO_OWNER": "${{ github.repository_owner }}",
                    "REPO_NAME": "${{ github.event.repository.name }}",
                    "PR_NUMBER": "${{ github.event.issue.number }}"
                  }
                }
              }
            }'
            --allowedTools "mcp__github_comment__update_claude_comment,mcp__github_inline_comment__create_inline_comment,Bash(gh pr view:*),Bash(gh pr diff:*)"

